### ISSUE TITLE
Empty tables

### ISSUE THREAD

**Issue by tom-porat-xyz** [trehn/hnmp#12]
In some instances, table function will never return results.

Adding the following print to line 298

``` python
print obj_table[-1][0][0].prettyPrint()
```

reveals that the oid was partially resolved by pynsmp

```
SNMPv2-SMI::enterprises."<snip>.2.4.3.4.2.1.1.15.12.49.55.50.46.51.49.46.51.49.46.51.52"
```

**Comment by TheFlyingCorpse** [comment]
I can confirm this fixes it :+1:

**Comment by trehn** [comment]
Thanks, I just pushed a new release to PyPI. And sorry for not getting around to verify this myself in time.

**Comment by TheFlyingCorpse** [comment]
It got fixed on SLES 11 SP3 with the above fix. Sadly the fix broke HNMP on Debian 8.x.

**Comment by trehn** [comment]
In what way, can you elaborate?
